module.exports = {
  PRESETS_UPDATED: 'presetsUpdated',
  NOW_PLAYING_UPDATED: 'nowPlayingUpdated',
  NOW_SELECTION_UPDATED: 'nowSelectionUpdated',
  VOLUME_UPDATED: 'volumeUpdated',
  BASS_UPDATED: 'bassUpdated',
  ZONE_UPDATED: 'zoneUpdated',
  INFO_UPDATED: 'infoUpdated',
  NAME_UPDATED: 'nameUpdated',
  ERROR: 'errorUpdate',
  GROUP_UPDATED: 'groupUpdated',
  BROWSE_UPDATED: 'browseUpdated',
  RECENTS_UPDATED: 'recentsUpdated',
  SOURCE_UPDATED: 'sourceUpdated',
  LANGUAGE_UPDATED: 'languageUpdated',
  USER_ACTIVITY_UPDATED: 'userActivityUpdated',
  USER_INACTIVITY_UPDATED: 'userInactivityUpdated',
  CONNECTION_STATE_UPDATED: 'connectionStateUpdated',
};
